version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: myjenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: always
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/lib/jenkins_workspace:/var/jenkins_home/workspace
      - /home/ubuntu/projects/cristian-web:/var/jenkins_home/workspace/cristian-web-page
volumes:
  jenkins_home:
